name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: Build
      run: |
        yarn install
        yarn run deploy
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@1.1.3
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build