name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: yarn install
      - name: Deploy to GH Pages
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          echo ${{ secrets.TOKEN }}
          git config --global user.name ${{ secrets.USERNAME }}
          git remote set-url origin https://${{ secrets.TOKEN }}@github.com/startupbruhs/bookstore-client.git
          yarn run deploy
